### ISSUE TITLE
Building is OK, not working.

### ISSUE THREAD

**Issue by omersiar** [HakonHystad/MFRC522_nested_attack#1]
Enabled `RC522_DBG`, still debugging is like hell. Sorry to bother, I compiled the code on RPi3 Model B, there is only `Timeout` printed on terminal. Tested MFRC522 module with python, SPI-py, etc. It seems it is working, I do not know how MFRC522 module accepting Raw SPI writes, how to know it is actually communicating? MFRC522 responding on SPI ? or Do we need to check registers?

```bash
pi@raspberrypi:~/MFRC522_nested_attack $ ./crack
Wrote register 2a: 54 80
Wrote register 2b: 56 a9
Wrote register 2c: 58 3
Wrote register 2d: 5a e8
Wrote register 15: 2a 40
Wrote register 11: 22 3d
Read register 14: 0
Wrote register 14: 28 3
crackKey
Recovering keys.. this may take some time
Read register 14: 0
Read register 14: 0
Wrote register 14: 28 3
sendReqA
piccIO
Wrote register 1: 2 0
Wrote register 4: 8 7f
Wrote register a: 14 80
Wrote register 9: 12 26
Wrote register d: 1a 7
Wrote register 1: 2 c
Read register d: 0
Wrote register d: 1a 80
Read register 4: 0
Read register 4: 0
Read register 4: 0
Read register 4: 0
Read register 4: 0
There is only "Read register 4: 0" 
```

**Comment by omersiar** [comment]
I'm total idiot.

**Comment by orlandoc01** [comment]
How did you solve this? I'm actually seeing the same thing and the answer isn't obvious to me haha 😁
