### ISSUE TITLE
got a 11 characters key...

### ISSUE THREAD

**Issue by ha-zhuzhu** [HakonHystad/MFRC522_nested_attack#11]
tried sereral times to get this weird key...does it mean it hadn't found the right key actually...

`Recovering keys.. this may take some time
<13.4998>Round 1: Found 1105597 possible keys, with most repeated key: 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
KEY FOUND TO BE:		54b71ef2079
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Time to crack: 13.4998
Timeout
`

happened the same in another sector:

`Recovering keys.. this may take some time
<8.83068>Round 1: Found 676754 possible keys, with most repeated key: 1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
KEY FOUND TO BE:		54b71ef2579
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Time to crack: 8.83068
Timeout`

**Comment by 3ndym10n** [comment]
tried 054b71ef2079 and it worked:)

**Comment by ha-zhuzhu** [comment]
tried 054b71ef2079 and it worked:)
